# Generated by Django 5.1.6 on 2025-02-19 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='organizers.organizer'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_events',
            field=models.ManyToManyField(blank=True, to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='eventPhotos',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.eventphoto'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='events.event'),
        ),
    ]
