# Generated by Django 5.1.6 on 2025-02-18 01:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventphoto_tag_tickettier_remove_event_created_by_and_more'),
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='organizers.organizer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='refundPolicy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='related_events',
            field=models.ManyToManyField(blank=True, to='events.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('MUSIC', 'Music'), ('SPORTS', 'Sports'), ('ART', 'Art'), ('FOOD', 'Food'), ('EDUCATION', 'Education'), ('TECH', 'Technology'), ('GAMES', 'Games'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='eventPhotos',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.eventphoto'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.tag'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='events.event'),
        ),
    ]
