# Generated by Django 5.1.6 on 2025-02-18 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_organizer_event_refundpolicy_and_more'),
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='organizers.organizer'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
