# Generated by Django 5.1.6 on 2025-02-19 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_remove_event_end_time_event_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay'), ('PAYPAL', 'PayPal')], default='CREDIT_CARD', max_length=20)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
                ('ticket_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.tickettier')),
            ],
        ),
    ]
