# Generated by Django 5.1.6 on 2025-02-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_eventphoto_tag_tickettier_remove_event_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=100)),
                ('main_city', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='organizer_profiles/')),
                ('notifications', models.JSONField(blank=True, default=list)),
                ('analytics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='organizers.organizer')),
                ('liked_events', models.ManyToManyField(blank=True, related_name='liked_by', to='events.event')),
            ],
        ),
    ]
