# Generated by Django 5.1.6 on 2025-02-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='organizer_profiles/')),
                ('notifications', models.JSONField(blank=True, default=list)),
                ('analytics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='organizers.organizer')),
                ('liked_events', models.ManyToManyField(blank=True, related_name='liked_by', to='events.event')),
            ],
        ),
    ]
