# Generated by Django 5.1.6 on 2025-02-19 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_end_time_event_contact_email_and_more'),
        ('organizers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='organizer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organizer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organizer',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organizer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizer_logos/'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='main_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='liked_events',
            field=models.ManyToManyField(blank=True, related_name='liked_by_organizers', to='events.event'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
