# Generated by Django 5.1.6 on 2025-02-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_end_time_event_contact_email_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attended_events',
            field=models.ManyToManyField(blank=True, related_name='attended_by_users', to='events.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_events',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='events.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='upcoming_events',
            field=models.ManyToManyField(blank=True, related_name='upcoming_for_users', to='events.event'),
        ),
    ]
